### ISSUE TITLE
ACID Transactions. Need driver for Nodejs --> to TokuMX

### ISSUE THREAD

**Issue by ooowos45653hs** [Tokutek/mongo#1176]
Hello,

I need a driver to access TokuMX from a Nodejs App and to perform real ACID Transactions. 

Indeed there do exist lots of MongoDB drivers for Nodejs (Javascript), but all of these drivers are incapable of performing ACID Transactions. Because of the inherent architecture of these drivers.

could you please be so kind and program a driver for Nodejs to perform ACID transactions?

thanks!

**Comment by Albermg7** [comment]
Hi,
I found your discussion really interesting cause it faces the problem our team is facing right now. 
I'd like to know if there have been some progress in TokuMX supporting transactions in the nodeJs driver or if you know some implementation that has worked on it. 
I checked out the project @leifwalsh recommended [here] (https://github.com/BlueRival/node-tokumx-native) but I cannot see any movement there since May 2014. 

Thanks a lot for explaining the problem anyway ;)
