### ISSUE TITLE
Cannot transition from not multi key to multi key in multi statement transaction

### ISSUE THREAD

**Issue by superisaac** [Tokutek/mongo#1224]
Here is how to create this issue:

```
mongo testbed
TokuMX mongo shell v2.0.0-mongodb-2.4.10
connecting to: testbed
> db.tx.ensureIndex({'vout.addrs': 1})
> var doc = {'vout': [{'addrs': ['hello']}, {'addrs': ['world']}]};
> db.runCommand('beginTransaction')
{ "status" : "transaction began", "ok" : 1 }
> db.tx.insert(doc)
Cannot transition from not multi key to multi key in multi statement transaction
```

**Comment by esmet** [comment]
That is correct

**Comment by superisaac** [comment]
can you tell the reason why it is correct?

**Comment by esmet** [comment]
Atomic rollback and snapshoting of the multi key indicator was hard to reason about at the time, so we disallowed that transition in an explicit transaction.

You can work around this not ensuring a collection is multi key before writing to it in an explicit txn.

**Comment by erikekblom** [comment]
I have also experienced this problem and the workaround was to drop all indexes. Later I created the multi key indexes again and have not since had this problem in the database in question.

Now I have created a new database and have the same problem on that and can make the same workaround.

Is there any way to determine whether a collection with multi key indexes is exposed to this restriction? I.e. determine if the "transition from not multi key to multi key" has already occurred?

Best regards
Erik Ekblom

**Comment by leifwalsh** [comment]
A query that uses a multikey index, when explain()ed, will show that fact. 

## 

Cheers,
Leif

**Comment by bitliner** [comment]
to me it is happening even without running a  multi-statement transaction (i do not run any beginTransaction). is this behavior as expected?

What the code does is to create some indexes, and insert some document.

Also in my case, if I drop the database, then it works fine
