### ISSUE TITLE
pymongo support of features specific to tokumx

### ISSUE THREAD

**Issue by flamby** [Tokutek/mongo#491]
hi,

happy about tokumx and using it w/ pymongo (using mongoengine), i'd like to know if you think that some tokumx features like transaction support needs to be adressed in the db drivers, particularly pymongo. and if so, if you plan to help the driver community in this regard, avoiding us to rely on future pymongo supporting tokumx features fork on github.

thanks in advance.

**Comment by paullo0106** [comment]
Hi @leifwalsh ,

I wonder that if declaring a transaction manually is needed for a single bulk insert operation

According to http://docs.tokutek.com/tokumx/tokumx-transactions.html: "In TokuMX, all operations are transparently wrapped in an atomic transaction on the server. The operation either completely succeeds or completely fails; there is no longer a "partial failure" result." 

So, if I execute: 

self.db[coll].insert_many([{'data':1}, {'data': 2}])

it should have the same effect as below:

db.command('beginTransaction')
self.db[coll].insert_many([{'data':1}, {'data': 2}])
db.command('commitTransaction')

is my understanding correct?

**Comment by paullo0106** [comment]
Hi @leifwalsh ,

I wonder that if declaring a transaction manually is needed for a single bulk insert operation

According to http://docs.tokutek.com/tokumx/tokumx-transactions.html: "In TokuMX, all operations are transparently wrapped in an atomic transaction on the server. The operation either completely succeeds or completely fails; there is no longer a "partial failure" result." 

So, if I execute: 

self.db[coll].insert_many([{'data':1}, {'data': 2}])

it should have the same effect as below:

db.command('beginTransaction')
self.db[coll].insert_many([{'data':1}, {'data': 2}])
db.command('commitTransaction')

is my understanding correct?

**Comment by leifwalsh** [comment]
That's correct, as long as the batch is small enough to be sent in one round trip. Pymongo will detect if the list is bigger than 16MB and if so it will break it into multiple batches. In this case you would need a transaction around those batches in order to get fully atomic batch writes. 



-- 
Cheers,
Leif

**Comment by paullo0106** [comment]
@leifwalsh , thanks very much for your quick response!

You mentioned that: "You need to make sure everything for a transaction goes over just one client and that other operations don't get interleaved with your transactions, so you need to use start_request"

Say, I have 3 threads share a same connection (please see the code below), and they would continue doing bulk write operation. Since each operation automatically belongs to an atomic transaction in TokuMX, so even if sometimes they might run into BulkWriteError for situations such as unique key violation, they should not interfere the operation executing in other threads, is that correct?
(I'm not sure if it's proper to consult for Tokumx problem here. If there is a better place to discuss such problem, please let me know.)

=====

import threading
import Queue
from pymongo.errors import BulkWriteError
import pymongo


class Worker(threading.Thread):

    def __init__(self, worker_id, data_queue, client):
        super(self.__class__, self).__init__()
        self.worker_id = worker_id
        self.data_queue = data_queue
        self.client = client

    def run(self):
        while True:
            try:
                data_list = self.data_queue.get()
                # some processing on data here, and then insert to database
                self.client.db['my_collection'].insert_many(data_list)
            except BulkWriteError as e:
                # some error handling here
                pass

client = pymongo.MongoClient()
data_queue = Queue.Queue()

for i in xrange(3):
    worker = Worker((i+1), data_queue, client)
    worker.daemon = True
    worker.start()

while True:
    data_list = get_list_of_data()  # generate a small list of dict as data and put into data_queue for Worker to handle
    data_queue.put(data_list)

data_queue.join()
client.close()

=====
