### ISSUE TITLE
SSL Support?

### ISSUE THREAD

**Issue by harrychan** [Tokutek/mongo#502]
MongoDB has SSL support http://docs.mongodb.org/manual/tutorial/configure-ssl/

Looking at using this, but the lack of SSL support seems to be a problem. Would prefer the data transfer to be encrypted. Any way to do this right now?

**Comment by saruye** [comment]
Hi, 

I tried using the vagrant box to compile tokumx which failed. I had to change the vagrant box to config.vm.box = "ubuntu/trusty64" because the other box didn't exist anymore. Then I had to comment out the lines in the .bash_profile. I wouldn't start otherwise. But now it fails with: (checked out at tag tokumx-2.0.1)

[ 73%] Building CXX object src/mongo/db/CMakeFiles/serveronly.dir/indexcursor.cpp.o
/home/vagrant/mongo/src/mongo/db/indexcursor.cpp: In constructor ‘mongo::IndexCursor::IndexCursor(mongo::CollectionData*, const mongo::IndexDetails&, const mongo::BSONObj&, const mongo::BSONObj&, bool, int, int)’:
/home/vagrant/mongo/src/mongo/db/indexcursor.cpp:180:97: error: invalid conversion from ‘bool (*)(void*)’ to ‘bool (*)(void*, uint64_t) {aka bool (*)(void*, long unsigned int)}’ [-fpermissive]
         cursor->c_set_check_interrupt_callback(cursor, cursor_check_interrupt, &_interrupt_extra);
                                                                                                 ^
/home/vagrant/mongo/src/mongo/db/indexcursor.cpp: In constructor ‘mongo::IndexCursor::IndexCursor(mongo::CollectionData*, const mongo::IndexDetails&, const boost::shared_ptr<mongo::FieldRangeVector>&, int, int, int)’:
/home/vagrant/mongo/src/mongo/db/indexcursor.cpp:214:97: error: invalid conversion from ‘bool (*)(void*)’ to ‘bool (*)(void*, uint64_t) {aka bool (*)(void*, long unsigned int)}’ [-fpermissive]
         cursor->c_set_check_interrupt_callback(cursor, cursor_check_interrupt, &_interrupt_extra);
                                                                                                 ^
make[2]: *** [src/mongo/db/CMakeFiles/serveronly.dir/indexcursor.cpp.o] Error 1
make[1]: *** [src/mongo/db/CMakeFiles/serveronly.dir/all] Error 2
make: *** [all] Error 2

Can you help me somehow ?

Regards, 
arne
